name: Remko Dirkmaat
favicon: null
layout_spectrum: 0.25768
typography_spectrum: 0.15612
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#aea586'
    - '#f5ddc3'
    - '#3a5e82'
    - '#763a28'
  brandStrength: 0.5625
  lightness: 0.5461880308575928
  saturation: 0.5
  rhythmicContrast: 0.8211959865875542
purpose: []
